package {{ .PackageName }}

type ApiGroup struct {
	// Code generated by github.com/gzpz/golf-sales-system/server Begin; DO NOT EDIT.

	// Code generated by github.com/gzpz/golf-sales-system/server End; DO NOT EDIT.
}
