package autocode

type ServiceGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin Begin; DO NOT EDIT.
	AutoCodeExampleService
	// Code generated by github.com/flipped-aurora/gin-vue-admin End; DO NOT EDIT.
}
