package autocode

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin Begin; DO NOT EDIT.
	AutoCodeExampleApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin End; DO NOT EDIT.
}
