export const hallSeat1 = [
  [
    { status: 1, number: 1, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 10, type: 'single' },
    { status: 1, number: 11, type: 'single' },
    { status: 1, number: 12, type: 'single' },
    { status: 1, number: 13, type: 'single' },
  ],
  [
    { status: 1, number: 1, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 10, type: 'single' },
    { status: 1, number: 11, type: 'single' },
    { status: 1, number: 12, type: 'single' },
    { status: 1, number: 13, type: 'single' },
  ],
  [
    { status: 1, number: 1, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 10, type: 'single' },
    { status: 1, number: 11, type: 'single' },
    { status: 1, number: 12, type: 'single' },
    { status: 1, number: 13, type: 'single' },
  ],
  [
    { status: 1, number: 1, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 10, type: 'single' },
    { status: 1, number: 11, type: 'single' },
    { status: 1, number: 12, type: 'single' },
    { status: 1, number: 13, type: 'single' },
  ],
  [
    { status: 0, number: 0, type: 'single' },
    { status: 0, number: 0, type: 'single' },
    { status: 0, number: 0, type: 'single' },
    { status: 0, number: 0, type: 'single' },
    { status: 1, number: 1, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 9, type: 'single' },
  ],
  [
    { status: 0, number: 0, type: 'single' },
    { status: 0, number: 0, type: 'single' },
    { status: 0, number: 0, type: 'single' },
    { status: 0, number: 0, type: 'single' },
    { status: 1, number: 1, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 9, type: 'single' },
  ],
  [
    { status: 0, number: 0, type: 'single' },
    { status: 0, number: 0, type: 'single' },
    { status: 0, number: 0, type: 'single' },
    { status: 0, number: 0, type: 'single' },
    { status: 1, number: 1, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 9, type: 'single' },
  ],
  [
    { status: 0, number: 0, type: 'single' },
    { status: 0, number: 0, type: 'single' },
    { status: 0, number: 0, type: 'single' },

    { status: 1, number: [1, 2], type: 'couple' },

    { status: 1, number: [3, 4], type: 'couple' },
    { status: 1, number: [5, 6], type: 'couple' },
    { status: 1, number: [7, 8], type: 'couple' },
    { status: 1, number: [9, 10], type: 'couple' },
  ],
];

export const hallSeat2 = [
  [
    { status: 1, number: 1, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 10, type: 'single' },
    { status: 1, number: 11, type: 'single' },
    { status: 1, number: 12, type: 'single' },
    { status: 1, number: 13, type: 'single' },
  ],
  [
    { status: 1, number: 1, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 10, type: 'single' },
    { status: 1, number: 11, type: 'single' },
    { status: 1, number: 12, type: 'single' },
    { status: 1, number: 13, type: 'single' },
  ],
  [
    { status: 1, number: 1, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 10, type: 'single' },
    { status: 1, number: 11, type: 'single' },
    { status: 1, number: 12, type: 'single' },
    { status: 1, number: 13, type: 'single' },
  ],
  [
    { status: 1, number: 1, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 10, type: 'single' },
    { status: 1, number: 11, type: 'single' },
    { status: 1, number: 12, type: 'single' },
    { status: 0, number: 0, type: 'single' },
  ],
  [
    { status: 1, number: 1, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 10, type: 'single' },
    { status: 1, number: 11, type: 'single' },
    { status: 1, number: 12, type: 'single' },
    { status: 1, number: 13, type: 'single' },
  ],
  [
    { status: 1, number: 1, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 10, type: 'single' },
    { status: 1, number: 11, type: 'single' },
    { status: 1, number: 12, type: 'single' },
    { status: 1, number: 13, type: 'single' },
  ],
  [
    { status: 1, number: 1, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 10, type: 'single' },
    { status: 1, number: 11, type: 'single' },
    { status: 1, number: 12, type: 'single' },
    { status: 1, number: 13, type: 'single' },
  ],
  [
    { status: 1, number: [1, 2], type: 'couple' },

    { status: 1, number: [3, 4], type: 'couple' },
    { status: 1, number: [5, 6], type: 'couple' },
    { status: 1, number: [7, 8], type: 'couple' },
    { status: 1, number: [9, 10], type: 'couple' },
    { status: 1, number: [11, 12], type: 'couple' },
    { status: 1, number: 13, type: 'single' },
  ],
];

export const hallSeat3 = [
  [
    { status: 0, number: 0, type: 'single' },
    { status: 1, number: 1, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 10, type: 'single' },
    { status: 1, number: 11, type: 'single' },
  ],
  [
    { status: 1, number: 1, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 10, type: 'single' },
    { status: 1, number: 11, type: 'single' },
    { status: 1, number: 12, type: 'single' },
  ],
  [
    { status: 1, number: 1, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 10, type: 'single' },
    { status: 1, number: 11, type: 'single' },
    { status: 1, number: 12, type: 'single' },
  ],
  [
    { status: 1, number: 1, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 10, type: 'single' },
    { status: 1, number: 11, type: 'single' },
    { status: 1, number: 12, type: 'single' },
  ],
  [
    { status: 0, number: 0, type: 'single' },
    { status: 0, number: 0, type: 'single' },
    { status: 0, number: 0, type: 'single' },
    { status: 1, number: 1, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 9, type: 'single' },
  ],
  [
    { status: 0, number: 0, type: 'single' },
    { status: 0, number: 0, type: 'single' },
    { status: 0, number: 0, type: 'single' },
    { status: 1, number: 1, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 9, type: 'single' },
  ],
  [
    { status: 0, number: 0, type: 'single' },
    { status: 0, number: 0, type: 'single' },
    { status: 0, number: 0, type: 'single' },
    { status: 1, number: 1, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 9, type: 'single' },
  ],
  [
    { status: 0, number: 0, type: 'single' },
    { status: 0, number: 0, type: 'single' },
    { status: 1, number: [1, 2], type: 'couple' },
    { status: 1, number: [3, 4], type: 'couple' },
    { status: 1, number: [5, 6], type: 'couple' },
    { status: 1, number: [7, 8], type: 'couple' },
    { status: 1, number: [9, 10], type: 'couple' },
  ],
];

export const hallSeat4 = [
  [
    { status: 1, number: 12, type: 'single' },
    { status: 1, number: 11, type: 'single' },
    { status: 1, number: 10, type: 'single' },
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 1, type: 'single' },
  ],
  [
    { status: 1, number: 12, type: 'single' },
    { status: 1, number: 11, type: 'single' },
    { status: 1, number: 10, type: 'single' },
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 1, type: 'single' },
  ],
  [
    { status: 1, number: 12, type: 'single' },
    { status: 1, number: 11, type: 'single' },
    { status: 1, number: 10, type: 'single' },
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 1, type: 'single' },
  ],
  [
    { status: 1, number: 12, type: 'single' },
    { status: 1, number: 11, type: 'single' },
    { status: 1, number: 10, type: 'single' },
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 1, type: 'single' },
  ],
  [
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 1, type: 'single' },
    { status: 0, number: 0, type: 'single' },
    { status: 0, number: 0, type: 'single' },
    { status: 0, number: 0, type: 'single' },
  ],
  [
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 1, type: 'single' },
    { status: 0, number: 0, type: 'single' },
    { status: 0, number: 0, type: 'single' },
    { status: 0, number: 0, type: 'single' },
  ],
  [
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 1, type: 'single' },
    { status: 0, number: 0, type: 'single' },
    { status: 0, number: 0, type: 'single' },
    { status: 0, number: 0, type: 'single' },
  ],
  [
    { status: 1, number: [10, 9], type: 'couple' },
    { status: 1, number: [8, 7], type: 'couple' },
    { status: 1, number: [6, 5], type: 'couple' },
    { status: 1, number: [4, 3], type: 'couple' },
    { status: 1, number: [2, 1], type: 'couple' },
    { status: 0, number: 0, type: 'single' },
    { status: 0, number: 0, type: 'single' },
  ],
];

export const hallSeat5 = [
  [
    { status: 1, number: 13, type: 'single' },
    { status: 1, number: 12, type: 'single' },
    { status: 1, number: 11, type: 'single' },
    { status: 1, number: 10, type: 'single' },
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 1, type: 'single' },
  ],
  [
    { status: 1, number: 13, type: 'single' },
    { status: 1, number: 12, type: 'single' },
    { status: 1, number: 11, type: 'single' },
    { status: 1, number: 10, type: 'single' },
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 1, type: 'single' },
  ],
  [
    { status: 1, number: 13, type: 'single' },
    { status: 1, number: 12, type: 'single' },
    { status: 1, number: 11, type: 'single' },
    { status: 1, number: 10, type: 'single' },
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 1, type: 'single' },
  ],
  [
    { status: 1, number: 13, type: 'single' },
    { status: 1, number: 12, type: 'single' },
    { status: 1, number: 11, type: 'single' },
    { status: 1, number: 10, type: 'single' },
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 1, type: 'single' },
  ],
  [
    { status: 1, number: 13, type: 'single' },
    { status: 1, number: 12, type: 'single' },
    { status: 1, number: 11, type: 'single' },
    { status: 1, number: 10, type: 'single' },
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 1, type: 'single' },
  ],
  [
    { status: 1, number: 10, type: 'single' },
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 1, type: 'single' },
    { status: 0, number: 0, type: 'single' },
    { status: 0, number: 0, type: 'single' },
    { status: 0, number: 0, type: 'single' },
  ],
  [
    { status: 1, number: 10, type: 'single' },
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 1, type: 'single' },
    { status: 0, number: 0, type: 'single' },
    { status: 0, number: 0, type: 'single' },
    { status: 0, number: 0, type: 'single' },
  ],
  [
    { status: 1, number: 11, type: 'single' },
    { status: 1, number: [10, 9], type: 'couple' },
    { status: 1, number: [8, 7], type: 'couple' },
    { status: 1, number: [6, 5], type: 'couple' },
    { status: 1, number: [4, 3], type: 'couple' },
    { status: 1, number: [2, 1], type: 'couple' },
    { status: 0, number: 0, type: 'single' },
    { status: 0, number: 0, type: 'single' },
  ],
];

export const hallSeat6 = [
  [
    { status: 1, number: 12, type: 'single' },
    { status: 1, number: 11, type: 'single' },
    { status: 1, number: 10, type: 'single' },
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 1, type: 'single' },
  ],
  [
    { status: 1, number: 12, type: 'single' },
    { status: 1, number: 11, type: 'single' },
    { status: 1, number: 10, type: 'single' },
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 1, type: 'single' },
  ],
  [
    { status: 1, number: 12, type: 'single' },
    { status: 1, number: 11, type: 'single' },
    { status: 1, number: 10, type: 'single' },
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 1, type: 'single' },
  ],
  [
    { status: 1, number: 12, type: 'single' },
    { status: 1, number: 11, type: 'single' },
    { status: 1, number: 10, type: 'single' },
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 1, type: 'single' },
  ],
  [
    { status: 1, number: 12, type: 'single' },
    { status: 1, number: 11, type: 'single' },
    { status: 1, number: 10, type: 'single' },
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 1, type: 'single' },
  ],
  [
    { status: 1, number: 10, type: 'single' },
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 1, type: 'single' },
    { status: 0, number: 0, type: 'single' },
    { status: 0, number: 0, type: 'single' },
  ],
  [
    { status: 1, number: 10, type: 'single' },
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 1, type: 'single' },
    { status: 0, number: 0, type: 'single' },
    { status: 0, number: 0, type: 'single' },
  ],
  [
    { status: 1, number: [10, 9], type: 'couple' },
    { status: 1, number: [8, 7], type: 'couple' },
    { status: 1, number: [6, 5], type: 'couple' },
    { status: 1, number: [4, 3], type: 'couple' },
    { status: 1, number: [2, 1], type: 'couple' },
    { status: 0, number: 0, type: 'single' },
    { status: 0, number: 0, type: 'single' },
  ],
];

export const hallSeat7 = [
  [
    { status: 1, number: 1, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 10, type: 'single' },
    { status: 1, number: 11, type: 'single' },
    { status: 1, number: 12, type: 'single' },
  ],
  [
    { status: 1, number: 1, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 10, type: 'single' },
    { status: 1, number: 11, type: 'single' },
    { status: 1, number: 12, type: 'single' },
  ],
  [
    { status: 0, number: 0, type: 'single' },
    { status: 1, number: 1, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 10, type: 'single' },
    { status: 1, number: 11, type: 'single' },
  ],
  [
    { status: 1, number: 1, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 10, type: 'single' },
    { status: 1, number: 11, type: 'single' },
    { status: 1, number: 12, type: 'single' },
  ],
  [
    { status: 1, number: 1, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 9, type: 'single' },
    { status: 1, number: 10, type: 'single' },
    { status: 1, number: 11, type: 'single' },
    { status: 1, number: 12, type: 'single' },
  ],
  [
    { status: 0, number: 0, type: 'single' },
    { status: 0, number: 0, type: 'single' },
    { status: 0, number: 0, type: 'single' },
    { status: 1, number: 1, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 9, type: 'single' },
  ],
  [
    { status: 0, number: 0, type: 'single' },
    { status: 0, number: 0, type: 'single' },
    { status: 0, number: 0, type: 'single' },
    { status: 1, number: 1, type: 'single' },
    { status: 1, number: 2, type: 'single' },
    { status: 1, number: 3, type: 'single' },
    { status: 1, number: 4, type: 'single' },
    { status: 1, number: 5, type: 'single' },
    { status: 1, number: 6, type: 'single' },
    { status: 1, number: 7, type: 'single' },
    { status: 1, number: 8, type: 'single' },
    { status: 1, number: 9, type: 'single' },
  ],
  [
    { status: 0, number: 0, type: 'single' },
    { status: 0, number: 0, type: 'single' },
    { status: 1, number: [1, 2], type: 'couple' },

    { status: 1, number: [3, 4], type: 'couple' },
    { status: 1, number: [5, 6], type: 'couple' },
    { status: 1, number: [7, 8], type: 'couple' },
    { status: 1, number: [9, 10], type: 'couple' },
  ],
];
