package autocode

type RouterGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin Begin; DO NOT EDIT.
	AutoCodeExampleRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin End; DO NOT EDIT.
}
